CREATE SCHEMA IF NOT EXISTS payment;
CREATE SCHEMA IF NOT EXISTS refund;
CREATE TABLE IF NOT EXISTS payment.shedlock (
    name       VARCHAR(64)  NOT NULL PRIMARY KEY,
    lock_until TIMESTAMP    NOT NULL,
    locked_at  TIMESTAMP    NOT NULL,
    locked_by  VARCHAR(255) NOT NULL
);
