jwt:
  secret-key: local-dev-jwt-secret-key-devticket-2025
  access-token-ttl: 1800000
  refresh-token-ttl: 604800000

logging:
  level:
    com.devticket: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true