jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-ttl: 1800000
  refresh-token-ttl: 604800000

logging:
  level:
    com.devticket: INFO

# 운영 환경 Swagger 비활성화
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  endpoint:
    health:
      show-details: never