spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/devticket?currentSchema=event
    username: devticket
    password: devticket
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: event
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      group-id: devticket-event
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 30s

service:
  member:
    url: http://localhost:8081

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.devticket: DEBUG
