#spring:
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

spring:
  datasource:
    # H2 메모리 DB를 사용하되, PostgreSQL 모드로 동작하도록 설정
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS event
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        default_schema: event
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 1s
    socket-timeout: 1s
