spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

jwt:
  secret-key: test-jwt-secret-key
  access-token-ttl: 1800000
  refresh-token-ttl: 604800000