spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: devticket-settlement
      auto-offset-reset: latest

external:
  commerce-base-url: http://commerce:8083
  member-base-url: http://member:8081
  event-base-url: http://event:8082

logging:
  level:
    com.devticket: INFO
